image:
  - Visual Studio 2019

version: 3.30.{build}

environment:
    matrix:
      - GEN: "Visual Studio 16 2019"
        CFG: Release
        ARCH: -A Win32
      - GEN: "Visual Studio 16 2019"
        CFG: Release
        ARCH: 

install:
    # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
    # logs.  See also http://help.appveyor.com/discussions/problems/4569
    # - del "C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
    - git submodule update --init --recursive

build_script:
    - cd build
    - cmake %ARCH% -G "%GEN%" ..
    - cmake --build . --config %CFG% --clean-first

