osx_image: xcode11
language: cpp
os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

script:
  - cd build
  - cmake ..
  - cmake --build . --config Release --clean-first
