language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

install:
  - git submodule update --init --recursive

script:
  - make cxxstd=c++11 config=release -j2
